INSERT INTO tb_category (name) VALUES ('Cat 1');
INSERT INTO tb_category (name) VALUES ('Cat 2');
INSERT INTO tb_category (name) VALUES ('Cat 3');

INSERT INTO tb_product (name) VALUES ('Prod 01 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 02 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 03 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 04 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 05 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 06 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 07 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 08 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 09 cats 1');
INSERT INTO tb_product (name) VALUES ('Prod 10 cats 1, 2, 3');
INSERT INTO tb_product (name) VALUES ('Prod 11 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 12 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 13 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 14 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 15 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 16 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 17 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 18 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 19 cats 2');
INSERT INTO tb_product (name) VALUES ('Prod 20 cats 1, 2, 3');
INSERT INTO tb_product (name) VALUES ('Prod 21 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 22 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 23 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 24 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 25 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 26 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 27 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 28 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 29 cats 3');
INSERT INTO tb_product (name) VALUES ('Prod 30 cats 1, 2, 3');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 3);

INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (20, 3);

INSERT INTO tb_product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (25, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (26, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (27, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (28, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (29, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (30, 2);
